n1 = int(input("Enter a number"))
n2 = int(input("Enter another number"))
print(f'Sum is {n1 + n2}')
print(f'Product is {n1 * n2}')
print(f'Substracted Result is {n1 - n2}')
print(f'After division is {n1 / n2}')